# Site
repository: praveencasimir/PraveenCasimirArockiasamy_Resume
favicon: images/resumeicon.png

# Content configuration version
version: 2

# Personal info
name: Praveen Casimir Arockiasamy
title: Technology Architect
email: praveen.casimir@gmail.com
# website: "https://drive.google.com/file/d/1JrVitQ5fpDGEv55TL6wOhGtmCj-lf8vV/view?usp=drive_link"
resume_link: https://drive.google.com/file/d/1JrVitQ5fpDGEv55TL6wOhGtmCj-lf8vV/view?usp=sharing
phone: +91 9884222580


# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: praveencasimir
# github_username:  praveencasimir
gmail_username: praveen.casimir@gmail.com
whatsapp_username: +919884222580
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: praveenarockiasamy
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
additional_links:
  - title: WhatsApp
    icon: fab fa-whatsapp
    url: https://wa.me/919884222580
  - title: Resume
    icon: fas fa-file-alt
    url: https://drive.google.com/file/d/1JrVitQ5fpDGEv55TL6wOhGtmCj-lf8vV/view?usp=sharing


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-praveen.jpg
about_content: | # this will include new lines to allow paragraphs
  An accomplished Integration Architect with over 17 years of experience in architecting middleware solutions using Oracle Fusion Middleware, specializing in SOA, DevOps, Apigee and AWS. Skilled in delivering innovative integration solutions across industries, I am currently advancing my expertise through a Master’s in Artificial Intelligence & Machine Learning.


content:
  - title: Technologies # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: Super awesome project
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        #   # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   #   icon: fab fa-github
        #   #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          GCP Apigee, AWS APIGateway, AWS Lambda, Webmethods IO APIGateway, Webmethods IO Integration, Oracle SOA Suite, Oracle Service Bus, Tableau, Data Science, Python, GitHub Actions, DevOps

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cognizant Technology Solutions Software Ltd
        link: https://www.cognizant.com/in/en
        link_text: cognizant.com
        sub_title: Technology Architect
        caption: February 2012 - Present
        # quote: >
        #   quote text here
        description: | # this will include new lines to allow paragraphs
            * Lead the design and implementation of integration architectures for clients, ensuring alignment with business objectives and technical requirements.
            * Spearheaded the establishment of SOA governance processes, guidelines and checklists.
            * Anchored the implementation of Apigee and WM.IO products, establishing governance, best practices and common services.
            * Achieved $300k+ in value savings by automating developer and operations team activities, significantly improving innovation metrics.
            * Reduced deployment time by 10x, enhancing efficiency for the development and operations teams.
            * Enhanced team capabilities by introducing new tools and practices, resulting in faster development, testing, and deployment.
            * Led multiple integration projects involving Oracle SOA Suite and Service Bus, optimizing middleware solutions for various clients using Oracle Fusion Middleware, Apigee, and WebMethods.IO. Led integration initiatives at Celgene Corporation, enhancing on-premises and cloud systems connectivity while migrating services and optimizing middleware solutions to improve operational efficiency.
            * Served as Scrum Master/Technical Lead for AstraZeneca’s AZIA Transformation project, streamlining integration technologies and governance processes to enhance efficiency and reduce maintenance costs across global operations.

      - layout: left
        title: Oracle Financial Services Software Ltd
        link: https://www.oracle.com/in/financial-services/
        link_text: oracle.com/in/financial-services/
        sub_title: Senior Consultant
        caption: Nov 2006 - Dec 2011
        # quote: >
        #   quote text here
        description: | # this will include new lines to allow paragraphs
            As Team Lead for the Payments Integration Accelerator Framework at OFSS, I lead the development of a middleware solution that streamlined financial message interactions, significantly enhancing implementation efficiency for banking clients. My leadership fostered knowledge transfer and technical excellence, ensuring robust system integrations across diverse.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: St.Josephs College of Engineering, Anna University, Chennai, Tamil Nadu, India
        caption: 2002 - 2006
        sub_title: B.Tech Information Technology
      - layout: top-middle
        title: Woolf University, Scaler
        caption: 2024 - 2026*
        sub_title: M.Sc Data Science & Machine Learning

  - title: Global Work Locations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Worked at
        image: images/locations.jpg
        description: |
          ![Worked Locations](images/locations.jpg)
          1. Bangalore, Karnataka, India
          2. Chennai, Tamil Nadu, India
          3. Pune, Maharashtra, India
          4. London, United Kingdom  
          5. Johannesburg, South Africa
          6. Amsterdam, Netherlands
          7. Sweden
          8. New Jersey, USA

        

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     content

      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
