# Site
repository: praveencasimir/PraveenCasimirArockiasamy_Resume
favicon: images/resumeicon.png

# Content configuration version
version: 2

# Personal info
name: Praveen Casimir Arockiasamy
title: Technology Architect
email: praveen.casimir@gmail.com
# website: "https://drive.google.com/file/d/1JrVitQ5fpDGEv55TL6wOhGtmCj-lf8vV/view?usp=drive_link"
resume_link: https://drive.google.com/file/d/1rrGkCqLxds_o4-zvhfw5zcgr_3LIWCJV/view?usp=sharing
phone: +91 9884222580


# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: praveencasimir
# github_username:  praveencasimir
gmail_username: praveen.casimir@gmail.com
whatsapp_username: +919884222580
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: praveenarockiasamy
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
additional_links:
  - title: WhatsApp
    icon: fab fa-whatsapp
    url: https://wa.me/919884222580
  - title: Resume
    icon: fas fa-file-alt
    url: https://drive.google.com/file/d/1JrVitQ5fpDGEv55TL6wOhGtmCj-lf8vV/view?usp=sharing


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-praveen.jpg
about_content: | # this will include new lines to allow paragraphs
  Technology Architect with over 17 years of experience in architecting middleware solutions using Oracle Fusion Middleware, specializing in SOA, DevOps, Apigee and AWS. Skilled in delivering innovative integration solutions across industries, I am currently advancing my expertise through a Master’s in Artificial Intelligence & Machine Learning.


content:
  - title: Technologies/Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: Super awesome project
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        #   # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   #   icon: fab fa-github
        #   #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          **Technologies:**
          Oracle SOA, Oracle Service Bus, Apigee, Wm.IO ApiGateway/Integration, CICD, DevOps, Open API, Automation Testing, PLSQL, BigQuery.

          **Tools:**
          GCP, AWS, Oracle Fusion Middleware, Webmethods, Git, GitHub, CICD, Jenkins, Junit, Apickli, GitHub Pages, Python Programming, Java, Node.js, Django, Tableau, Oracle Integration Cloud, Oracle Open Search, Subversion.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cognizant Technology Solutions Software Ltd
        link: https://www.cognizant.com/in/en
        link_text: cognizant.com
        sub_title: Technology Architect
        caption: January 2012 - Present (12 years 11 months)
        description: | # this will include new lines to allow paragraphs
            **Client: Trane Technologies**

            - Architected SubInventory transfers via Apigee to EBS based on Surgere RFID movements
            - API based architecture for Compliance Rating of Projects and SalesOrders with E2Open
            - Modernising Architecture for Oracle EBS Payments and Bank Statements integration with Finastra, JPMC...
            - Enabling headless search for Salesforce Portal with YEXT integration
            - Automated Address validations for Coupa with Melissa API and callbacks
            - Reducing 50% manual efforts by enabling change data capture sync from Salesforce to ComfortSite
            - Implementing Apigeelint and custom validation rules on PR Process for Apigee Proxy developments
            - Establishing approval process in the CICD for Proxy deployments
            - Automation testing implementation with Postman/newman and apickli for API testing
            - GCP Apigee, Webmethods.IO APIGateway/Integration product feasibility and patterns implementation for adoption
            - Enabling Salesforce ECommerce integrations Architecture with CyberSource, Vertex, FedEx and UPS
            - Open API spec templatization and Documentation with GitHub Pages
            - Algorithm for Fusion Middleware dependency resolution and sequencing logic in CI/CD with Python to facilitate Mono Repo deployments for 500+ services.

            **Client: Celgene - Bristol Meyers Squibb**

            - Migrated entrie Middleware services between datacenters with effective test filteration and automated network checks for firewall verifications. Improving testing time from days to minutes.
            - Automated testing to assist Migration verification
            - Automated EBS Manufacturing recipe imports with parallel processing features improving productivity by 50%
            - Migration of existing services to Oracle Fusion Middleware to 12cR2
            - Architected various integrations with Salesforce, EBS, Workday, Peoplesoft and various SaaS systems.
            - Improving Drug Safety import process via async integration Architecture
            - API design and data gathering for Drug Safety IBM Watson integration
            - Automated Fusion deployment process with Jenkins and ant.

            **Client: AstraZeneca**

            - Served as Scrum Master/Technical Lead for AstraZeneca’s AZIA Transformation project, streamlining integration technologies and governance processes to enhance efficiency and reduce maintenance costs across global operations.
            - Technical Lead for US Fusion Middleware support operations offshore.
            - Production support lead
            - Mentoring team members and Knowledge Video library creation

            Worked in Chennai India and New Jersey USA

      - layout: left
        title: Oracle Financial Services Software Ltd
        link: https://www.oracle.com/in/financial-services/
        link_text: oracle.com/in/financial-services/
        sub_title: Senior Consultant
        caption: November 2006 - December 2011 (5 years 2 months)
        description: | # this will include new lines to allow paragraphs
            As Team Lead for the Payments Integration Accelerator Framework at OFSS, led the development of a middleware solution that streamlined financial message interactions, significantly enhancing implementation efficiency for banking clients. Fostered knowledge transfer and technical excellence, ensuring robust system integrations across diverse locations including Chennai, Bengaluru, Pune, Johannesburg, Amsterdam, Sweden, and London.

  - title: Technical Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | # this will include new lines to allow paragraphs
          - Apigee proxy sharedflow target flow visualization
          - Apigee KVM rendering for Operations team visibility
          - Metabase visualization for planning migration and improving efficiency
          - Walmart/Netflix/Aerofit Data Analytics and Visualization (Scaler)
          - Enthusiast PineScript developer

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: St.Josephs College of Engineering, Anna University, Chennai, Tamil Nadu, India
        caption: 2002 - 2006
        sub_title: B.Tech Information Technology
      - layout: top-middle
        title: Woolf University, Scaler
        caption: 2024 - 2026*
        sub_title: M.Sc Data Science & Machine Learning

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Oracle Cloud Infrastructure 2023 Foundations Associate Certification 
        caption: 2024
        sub_title: 1Z0-1085-23
      - layout: top-middle
        title: Oracle Cloud Infrastructure 2023 AI Foundations Associate Certification 
        caption: 2024
        sub_title: 1Z0-1122-23


  - title: Global Work Locations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Worked at
        image: images/locations.jpg
        description: |
          ![Worked Locations](images/locations.jpg)
          1. Bangalore, Karnataka, India
          2. Chennai, Tamil Nadu, India
          3. Pune, Maharashtra, India
          4. London, United Kingdom  
          5. Johannesburg, South Africa
          6. Amsterdam, Netherlands
          7. Sweden
          8. New Jersey, USA

        

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     content

      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
